#   scp -r smart-admin.jar root@101.200.190.174:/data/smart-admin
#   ssh root@101.200.190.174
#  13683336403-n
smarthome:
  refresh:
    state: false
  request:
    state: false
    header: false
  response:
    state: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3341/smarthome?setUnicode=true&characterEncoding=utf8
    username: smarthome
    password: edluja96TI953Ptz
    #hikari数据库连接池
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1
        min-idle: 0
    password: 6jXL95Iv2BFisJNB
    port: 6333
    timeout: 1000